# Generated by Django 5.1.7 on 2025-06-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('order_number', models.CharField(max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_inventory', to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_inventory', to='inventory.location')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_inventory', to='inventory.procurement')),
            ],
            options={
                'unique_together': {('item', 'procurement', 'location')},
            },
        ),
    ]
