# Generated by Django 5.1.7 on 2025-07-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dead_stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
