# Generated by Django 5.1.7 on 2025-07-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_discardrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discardrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user'),
        ),
    ]
