# Generated by Django 5.1.7 on 2025-06-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorybylocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorybylocation',
            old_name='available_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dead_stock_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
    ]
