# Generated by Django 5.1.7 on 2025-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_totalinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dead_stock_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
