# Generated by Django 5.1.7 on 2025-06-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_dead_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_main_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='totalinventory',
            name='last_stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='inventory.stockmovement'),
        ),
    ]
