# Generated by Django 5.1.7 on 2025-07-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_discardrequest_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_at_location', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('main_inventory_manager', 'Main Inventory Manager'), ('inventory_manager', 'Inventory Manager')], max_length=25),
        ),
        migrations.CreateModel(
            name='ContractSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='contract_schedules/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_schedules', to='inventory.procurement')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contract_schedules', to='inventory.user')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AmendmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='amendments/')),
                ('reason', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amendment_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_amendments', to='inventory.user')),
                ('contract_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='inventory.contractschedule')),
            ],
            options={
                'ordering': ['-amendment_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('procurement', 'Procurement'), ('transfer', 'Transfer')], max_length=20)),
                ('order_id', models.PositiveIntegerField()),
                ('delivery_type', models.CharField(choices=[('full', 'Full Delivery'), ('partial', 'Partial Delivery')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('document', models.FileField(upload_to='delivery_notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_delivery_notes', to='inventory.user')),
            ],
            options={
                'ordering': ['-delivery_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_type', models.CharField(choices=[('full', 'Full Receipt'), ('partial', 'Partial Receipt')], max_length=20)),
                ('receiving_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_notes', to='inventory.deliverynote')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='inventory.user')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_receiving_notes', to='inventory.user')),
            ],
            options={
                'ordering': ['-receiving_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='in_transit', max_length=20)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_from', to='inventory.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='inventory.item')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transits_received', to='inventory.user')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_sent', to='inventory.user')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_to', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='inventory.item')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='inventory.deliverynote')),
            ],
            options={
                'unique_together': {('delivery_note', 'item', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='ReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='inventory.item')),
                ('receiving_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='inventory.receivingnote')),
            ],
            options={
                'unique_together': {('receiving_note', 'item', 'lot_number')},
            },
        ),
    ]
