# Generated by Django 5.1.7 on 2025-07-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dead_stock_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dead_stock_quantity',
        ),
    ]
