# Generated by Django 5.1.7 on 2025-06-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_location_is_main_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_main_store',
        ),
    ]
