# Generated by Django 5.2.3 on 2025-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='procurement_documents/'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
