# Generated by Django 5.1.7 on 2025-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockrequest_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='requester_name',
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='inventory.user'),
        ),
        migrations.DeleteModel(
            name='SendingStockRequest',
        ),
    ]
