# Generated by Django 5.1.7 on 2025-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user_count',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
