# Generated by Django 5.1.7 on 2025-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_procurementitem_model_and_remove_item_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Purchase Order', 'Purchase Order'), ('MOU (Email)', 'MOU (Email)'), ('Internal Memo', 'Internal Memo'), ('Donation Letter', 'Donation Letter'), ('Invoice', 'Invoice')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Donation', 'Donation'), ('Transfer', 'Transfer')], max_length=20, null=True),
        ),
    ]
