# Generated by Django 5.1.7 on 2025-06-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='discardeditem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discarded_items', to='inventory.location'),
        ),
    ]
