# Generated by Django 5.1.7 on 2025-06-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sendingstockrequest_delete_stockrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('Damaged', 'Damaged'), ('Obsolete', 'Obsolete'), ('Expired', 'Expired'), ('Other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_items', to='inventory.user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discarded_items', to='inventory.item')),
            ],
        ),
    ]
