# Generated by Django 5.1.7 on 2025-07-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_department_deleted_at_department_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.department'),
        ),
    ]
