# Generated by Django 5.1.7 on 2025-06-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_discardeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('export_pdf', models.FileField(blank=True, null=True, upload_to='report_exports/pdf/')),
                ('export_excel', models.FileField(blank=True, null=True, upload_to='report_exports/excel/')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.user')),
            ],
        ),
    ]
