# Generated by Django 5.1.7 on 2025-06-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='procurement',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Purchase Order', 'Purchase Order'), ('MOU (Email)', 'MOU (Email)'), ('Internal Memo', 'Internal Memo'), ('Donation Letter', 'Donation Letter'), ('Invoice', 'Invoice')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Donation', 'Donation'), ('Transfer', 'Transfer')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.procurement')),
            ],
        ),
    ]
