# Generated by Django 5.1.7 on 2025-07-31 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_department_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='department',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='inventory.department'),
        ),
    ]
