# Generated by Django 5.1.7 on 2025-07-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_department_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
