# Generated by Django 5.1.7 on 2025-08-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_update_department_user_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user_count',
        ),
    ]
